WIP: Allows to migrate/detach project to/from Mergin
lutraconsulting/input pull request #1061
Opened 2020-12-10 16:05 UTC by sklencar

closes #614

2021-01-05 16:56 UTC, tomasMizera requested changes
Looking good, good job!

Some notes (not needed to change now, may be discussed and changed in future):
 - Detach is visible and clickable from GUI, is this intended?
 - If user detaches a project, it is not possible to upload it back again - because project with such name already exists on mergin. Maybe we can in future ask for desired project name?
 - Since detaching _cannot_ be undone, what about some confirmation window to not detach project by accident?

After talk with @sklencar, detach should not be visible and clickable from GUI, so I am setting this PR as `request changes`.

2021-01-05 16:56 UTC, tomasMizera commented on app/merginapi.cpp
> +  emit notify( QStringLiteral( "Project detached from Mergin" ) );
Translate string `tr ()`

2021-01-05 16:56 UTC, tomasMizera commented on app/merginapi.cpp
> +  emit notify( QStringLiteral( "Project detached from Mergin" ) );
Also messages from server (like `Project XYZ already exists!`) are probably not being translated but showed to user in english, maybe we could change that in future

2021-01-06 11:40 UTC, sklencar commented
Detached functionality is hidden in gui. It would be good to discuss what to do with orphaned projects at some point.

Good point that we probably don't have support for getting translated text from the server. Also good topic to discuss - I have just opened an issue to not forget about it.

2021-01-06 13:33 UTC, tomasMizera reviewed
I confirm that detach is hidden. 

One UX note: after clicking on Upload to Mergin, there is no visual feedback that project is being uploaded, neither a popup that project was successfully uploaded to Mergin. @sklencar I suggest creating an issue for that / adding just a toast after successful upload for now to not block this big PR with UX

2021-01-06 13:33 UTC, tomasMizera approved these changes

2021-01-08 08:49 UTC, wonder-sk commented on app/qml/MerginProjectPanel.qml
> +                  imageSource: contextMenu.isMerginProject ? InputStyle.detachIcon : InputStyle.uploadIcon
Better to remove the "Detach from Mergin" text and the detach icon to avoid confusion?

2021-01-08 08:51 UTC, wonder-sk commented
If there is no feedback after one presses upload button, that's something we'll need to sort out - there should be the same kind of feedback like when doing ordinary sync of a project, including a cancel button...

2021-01-08 08:52 UTC, wonder-sk commented
(but we can do it separately on another PR - so please just file a ticket for it)

2021-01-08 10:50 UTC, sklencar commented
An issue related to notification has been created: https://github.com/lutraconsulting/input/issues/1086
Conflicts resolved

2021-01-11 10:10 UTC, merged