Fix of opening account panel after sign out
lutraconsulting/input pull request #1369
Opened 2021-04-30 14:24 UTC by sklencar

Fix of really annoying bug that has been introduces after CE support PR.

**Story behind:**
When a user signs out, userInfo, subscriptionInfo and authData are cleared. After CE support PR a new signal has been introduced to update user info, when subscription has changed (storage has to be updated - this extra call was needed mostly for tests). 

**The cause:**
This extra call for userInfo triggers authorization, which opens an extra Login page in the stackview. This extra page is unexpected and stackview pops out Login page instead of Account page (where user clicks on Sign out button). Therefore AccountPage was still present (and empty)

**Solution:**
Since after the sign out, all user data are cleared, there is not need to request userInfo at all. Simple condition was added to prevent it.

Another possible solution would be to use different signals for clearing user data and where data are updated. 

closes #1367

2021-05-03 11:41 UTC, PeterPetrik commented on core/merginapi.h
> +     * Calls user info only when has authData, otherwise slots catches the signal from clering user data after signing out.
clering -> typo

2021-05-05 06:51 UTC, PeterPetrik requested changes
now in the "subscribtion plans" panel I do not see storage and the end date

<img width="609" alt="Screen Shot 2021-05-05 at 8 49 47" src="https://user-images.githubusercontent.com/804608/117105716-e38bb300-ad7e-11eb-9ba4-23fc34d9e800.png">

2021-05-05 09:34 UTC, sklencar commented
Did you test on desktop build? Are actually purchasing plans available for regular (non-testing) desktop build? FetchPurchasingPlans has successful reply, but gets empty data for desktop.

The issue is present at least since release 0.9 for desktop builds. The issue is not present for current branch, master or 0.9.0 release on iOS.
I would create a separate ticket for it since it seems to be unrelated to changes of this PR.

2021-05-05 09:54 UTC, PeterPetrik commented
server sends the empty data?

2021-05-05 14:37 UTC, sklencar commented
Correct behaviour is that manageSubscirptionPlans triggers Merign page as it does on Android

2021-05-06 05:39 UTC, merged