Separate map component
lutraconsulting/input pull request #1577
Opened 2021-08-03 06:48 UTC by tomasMizera

Separated map component with all its relative components (compass, position kit, digitizing controller, toolbar,..) to subfolder called `map`. There is a new qml type called `MapWrapper.qml` that wraps map functionalities like showing map, identifying features and 
recording geometry.

This PR do not change anything visually in app.

Note:
 - This separation was must in order to close #1551 
 - Currently it is not possible to edit geometry, will be included in next PR together with adding geometry for new linked features
 - I had to add all icons to `InputStyle` with `qrc:/` prefix because qml files moved

2021-08-03 12:49 UTC, sklencar requested changes
Good job, generally looks good, just small notes.

However I found a bug related to digitizing - while changing map themes and visible layers, it could happen that no digitizing layer is selected and therefore Input crash while adding a point.

To replicate it with input-testing/tc04_recording:
1. Open the project and click on record button
2. Make sure that (point) layer is selected as digitizng layer and a point can be created
3. Change a map theme from `Points` to `Paths and polygons`. 
4. Click on the record button and check if any layer for digitizing is selected -> here I can see no layer is selected and therefore the app crashed after adding a point.

2021-08-03 12:49 UTC, sklencar commented on app/qml/map/LoadingIndicator.qml
> +import ".."
Does it need such import?

2021-08-03 12:49 UTC, sklencar commented on app/qml/map/MapWrapper.qml
> +      name: "View"
We used to name states starting with small letter as well as can be seen [here. in coding conventions](https://doc-snapshots.qt.io/qt6-dev/qml-codingconventions.html).
Any particular reason while states starts with a capital letter?

2021-08-03 12:49 UTC, sklencar commented on app/qml/map/MapWrapper.qml
> +        //       mapCanvas.forceActiveFocus()
probably leftover?

2021-08-03 12:49 UTC, sklencar commented on app/qml/map/MapWrapper.qml
> +        name: "Good"
Same as naming for _map states

2021-08-03 12:49 UTC, sklencar commented on app/qml/map/MapWrapper.qml
> +    link: "https://help.inputapp.io/howto/gps_accuracy"
Better to add it to InputHelp among other links

2021-08-03 12:49 UTC, sklencar commented on app/qml/qml.qrc
> +        <file>map/MapWrapper.qml</file>
Since introducing new subfolder (and generally redefining the list), could be good to have it sorted alphabetically.

2021-08-03 13:40 UTC, sklencar commented
Additionally, icons are broken:
Account page is missing icons with error message(s): 
`qrc:/components/TextWithIcon.qml:35:5: QML Image: Cannot open: qrc:/components/account.svg`

<img width="402" alt="Screenshot 2021-08-03 at 15 38 09" src="https://user-images.githubusercontent.com/6735606/128025211-5a996f55-b2c6-4f54-a364-1caa5e2e2811.png">

2021-08-04 08:47 UTC, tomasMizera commented on app/qml/map/LoadingIndicator.qml
> +import ".."
Yes, for InputStyle

2021-08-04 09:15 UTC, tomasMizera commented on app/qml/InputStyle.qml
> +    property string cameraIcon: "qrc:/add_photo.svg"
Tried to divide it into related categories

2021-08-04 09:16 UTC, tomasMizera commented
@sklencar all notes are resolved

2021-08-04 10:06 UTC, sklencar approved these changes

2021-08-04 10:52 UTC, merged