Add attention banner
lutraconsulting/input pull request #1752
Opened 2021-11-11 12:38 UTC by varmar05

PR adds 'Attention required' banner in Project Panel. Its purpose is to draw attention of user that there is some issue which needs to be resolved in Mergin dashboard.

Appearance of the banner depends on flag coming from server response (`/v1/user/service`). Status is refreshed on panel open action to ensure current state is reflected before sync.

Resolves #1731 

![input_banner](https://user-images.githubusercontent.com/23185498/141299302-3f681b77-8de2-46ae-b0a6-6a436b24eced.png)

2021-11-11 14:21 UTC, PeterPetrik commented
does it work with Mergin CE ?

2021-11-11 16:00 UTC, tomasMizera requested changes
Great job!

2021-11-11 16:00 UTC, tomasMizera commented on core/merginsubscriptioninfo.cpp
> +  mActionRequired = docObj.value( QStringLiteral( "action_required" ) ).toBool();
As a rule of thumb, we only set property value when we know it has changed (and emit its specific signal):

```suggestion
  bool isActionRequired = docObj.value( QStringLiteral( "action_required" ) ).toBool();
  if ( isActionRequired != mActionRequired )
  {
    mActionRequired = isActionRequired;
  } 
```

2021-11-12 11:47 UTC, varmar05 commented
> does it work with Mergin CE ?

yes, tested with CE server (banner never appears as it is not supported)

2021-11-12 12:35 UTC, tomasMizera approved these changes

2021-11-12 18:17 UTC, tomasMizera commented
I will test this on Monday on iOS and close it then

2021-11-18 14:03 UTC, merged