Add delete account functionality (fix #1896)
lutraconsulting/input pull request #2083
Opened 2022-05-11 11:38 UTC by alexbruy

Add button to the Account page allowing user to remove Mergin Maps account.
![зображення](https://user-images.githubusercontent.com/776954/167840689-e006eadf-b3d9-4e67-bcb6-6b18bb2e3354.png)
When account removal requested user is informed that all local projects will be removed from the device and that he should manually cancel Apple subscription if there is one. Also user should type his username in the text field before proceeding.
![зображення](https://user-images.githubusercontent.com/776954/167840625-25541a41-36cd-4bbf-abf8-abea2b464f94.png)
In case if account removal failed an error message is shown.

Fixes #1896.

2022-05-11 16:14 UTC, tomasMizera requested changes
Thanks Alex 🚀 , here are my notes:

1. From my point of view, we should first try to delete an account on Mergin and only after this step succeeds continue with the removal of local projects and local auth. The thing is that Mergin server that a user is using might not even support `DELETE` which would result in simple removal of all downloaded projects.
2. When user hits `Yes` in account deletion dialog, there should be a _busy indicator_ running showing that we are doing something on background. It should keep running while wait for server response, delete all local projects and remove auth.
3. I know that styling of QML dialog might be depressing 😬, especially with buttons. However, could we make it look more like the one below? I suggest to keep the standard buttons and not worry about styling them, so only style the background and text of the popup (e.g. give it some margins from screen edges, center popup on a screen, blur/dim everything around the popup - this should be possible out of the box with Dialog coming from `qtquick controls2`)

<img src="https://user-images.githubusercontent.com/22449698/167894478-0e5ae6d7-dfa4-420e-88fd-9dabea37834e.png" width=300>

 4. Lastly, I know we had a discussion about which library to use for dialogs, it seems that QT recommends to use QtQuick controls2 variant. Mind the comment here: https://doc.qt.io/qt-5/qml-qtquick-dialogs-dialog.html#details 
![image](https://user-images.githubusercontent.com/22449698/167897270-a9d8b032-9408-4df7-a773-106e0846952e.png)

2022-05-11 16:14 UTC, tomasMizera commented on app/qml/AccountPage.qml
> +      ColumnLayout {
This should most likely be binded to `contentItem:`

```suggestion
      contentItem: ColumnLayout {
```

2022-05-12 06:42 UTC, alexbruy commented
@tomasMizera hope you are happy now

2022-05-20 09:16 UTC, tomasMizera commented
@alexbruy regarding failing tests, it might be that you need to wait LONG_REPLY instead:

```
FAIL!  : TestMerginApi::testAccountDelete() 'spy.wait( TestUtils::SHORT_REPLY )' returned FALSE. ()
   Loc: [../input/app/test/testmerginapi.cpp(2491)]
```

2022-06-06 08:05 UTC, jozef-budac commented
I am not sure it we fulfill the requirement with this change. After deletion of the user, the account is not deleted, it is just deactivated. According apple quidelines:
 "It’s insufficient to only provide the ability to temporarily disable or deactivate an account. People should be able to delete the account along with their personal data."

Right now, when I delete account in input, I am not able to register again, as the username exists and when I try to log in with deleted account in input od web app, it says, **Account is not activated**

2022-06-06 10:36 UTC, PeterPetrik commented
Lets see if they accept it or not,. we can change it after Apple review if needed. I think it is safer to wait 5 days as it is now, so in case of the unwanted removal they can still reactivate the account via support

2022-06-06 10:36 UTC, merged